inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - lib/**/*
    - Gemfile
    - Rakefile
    - Thorfile
  Exclude:
    - example/**/*
    - bin/convection
    - 'lib/convection/model/template/mapping.rb' # Something is causing this file to fail

Encoding:
 Enabled: false
RescueModifier:
 Enabled: false
HashSyntax:
 Enabled: false
SpaceInsideStringInterpolation:
  Enabled: false
Performance/RedundantBlockCall:
  Enabled: false
Style/SignalException:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - 'lib/convection/dsl/terraform_intrinsic_functions.rb'

# Ignore block length limits for DSLs
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

# AbcSize:
#   Max: 24
# ClassLength:
#   Max: 256
# CyclomaticComplexity:
#   Max: 12
# MethodLength:
#   Max: 32
# PerceivedComplexity:
#   Max: 12
